# Generated by Django 3.0.6 on 2020-05-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_voted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_inside',
        ),
    ]
